import type { SiteConfig } from "./types";

/** Local fallback mirrored from the public Notion database. */
export const seedSite: SiteConfig = {
  title: "Esther Yang",
  tagline: "Let learning as a experience, not transaction.",
  pages: [
    {
      id: "about",
      title: "About",
      slug: "about",
      description:
        "Hello, Esther is a confused human being, from Taiwan.",
      icon: "😀",
      template: "post",
      publish: true,
      inMenu: true,
      inList: true,
      tags: [],
      date: null,
      body: "",
    },
    {
      id: "work",
      title: "Work",
      slug: "work",
      description:
        "Software Engineering, Machine Learning, Data Science @ ex-Meta / Minerva University / ex-Google Research Fellow",
      icon: "🤖",
      template: "post",
      publish: true,
      inMenu: true,
      inList: true,
      tags: [],
      date: null,
      body: "",
    },
    {
      id: "now",
      title: "Now",
      slug: "now",
      description: "Problems I'm working on.",
      icon: "🖊️",
      template: "post",
      publish: true,
      inMenu: true,
      inList: true,
      tags: [],
      date: null,
      body: "",
    },
    {
      id: "play",
      title: "Play",
      slug: "play",
      description: "Play is another way to learn.",
      icon: "🌚",
      template: "post",
      publish: true,
      inMenu: true,
      inList: true,
      tags: [],
      date: null,
      body: "",
    },
    {
      id: "learn",
      title: "Learn",
      slug: "learn",
      description: "Learning is me. I am learning.",
      icon: "🌝",
      template: "post",
      publish: true,
      inMenu: true,
      inList: true,
      tags: [],
      date: null,
      body: "",
    },
  ],
};
