export type MetaRow = { label: string; value: string; link?: boolean };
export type FeatureItem = { title: string; body: string };
export type Plate = {
  device: "raw" | "figure" | "phone" | "tablet" | "laptop" | "desktop";
  caption: string;
  aspect?: number;
};

export type WorkProject = {
  slug: string;
  plate: string;
  year: string;
  medium: string;
  title: string;
  purpose: string;
  work: string | string[];
  results: string | string[];
  features?: string[];
  featuresCompact?: FeatureItem[];
  plates?: Plate[];
  confidential?: string;
  meta: MetaRow[];
};

export const WORK_PROJECTS: WorkProject[] = [
  {
    slug: "email",
    plate: "I",
    year: "2024",
    medium: "software · ml · side project",
    title: "AI Auto Email Follow Up",
    purpose:
      "Following up on job applications was a tedious yet important task. To address this, we implemented an automated system that sends follow-up emails after three days if no response is received.",
    work:
      "If an email you sent to recruiters or outreach hasn't been responded to for three days, GPT will generate a follow-up draft based on your past conversation for you.",
    results: "Over 60 people signed up and the demo received 40,000+ views.",
    features: [
      "An email label to filter recruiters vs non-recruiters.",
      "For labeled emails that haven't been replied to for three days, a GPT drafts a follow-up email based on your prior conversation.",
      "The draft sends to your inbox to remind you to follow up, and you can customize it before sending.",
    ],
    featuresCompact: [
      { title: "Label", body: "Distinguishes recruiters from everyone else." },
      { title: "3-day nudge", body: "A GPT drafts a follow-up rooted in the thread." },
      { title: "Inbox draft", body: "Lands as a reminder — refine and send." },
    ],
    plates: [
      {
        device: "raw",
        caption:
          "Gmail thread view, with the new label and recent labelled threads",
        aspect: 16 / 10,
      },
    ],
    meta: [
      { label: "Year", value: "2024" },
      { label: "Type", value: "Solo side project" },
      { label: "Stack", value: "GPT-4 · Gmail API · Python" },
      { label: "Demo", value: "40K+ views ↗", link: true },
    ],
  },
  {
    slug: "minerva",
    plate: "II",
    year: "2023",
    medium: "research · nlp · school project",
    title: "How English Fluency Affects Grading at Minerva",
    purpose:
      "My school, Minerva, comprises non-English native students from 40+ countries. If a classmate speaks like Shakespeare, but I speak simply like a kindergartener — will the professor bias their grading?",
    work:
      "This project examines the potential bias in students' grades due to English fluency through NLP analysis. Using topic modelling, clustering, hypothesis testing, and neural-network analyses, I investigated the influence of word choice, readability, and language sophistication on professors' evaluations of student knowledge.",
    results:
      "Positive and significant grade-fluency correlations across all colleges — least significant for the Computer Science college.",
    plates: [
      {
        device: "figure",
        caption: "Methodology — flowchart of the analytical pipeline",
        aspect: 16 / 10,
      },
    ],
    meta: [
      { label: "Year", value: "2023" },
      { label: "Type", value: "School research · Minerva" },
      { label: "Stack", value: "Python · NLP · scikit-learn" },
      { label: "Paper", value: "Methodology ↗", link: true },
    ],
  },
  {
    slug: "learn",
    plate: "III",
    year: "2024",
    medium: "engineering · ai · founding role",
    title: "Founding AI Engineer @ Learn.xyz",
    purpose:
      "The content and image quality of mini courses generated by AI had been low. The job: raise the floor across 60K+ courses without slowing the team down.",
    work: [
      "Deployed the entire backend pipeline, integrating Firebase and GCP, leveraging asynchronous processing, content moderation, and error handling.",
      "Engineered a real-time Slack integration on top of the Firebase backend, enabling the internal team to moderate and delete unethical content.",
      "Integrated vector embeddings on Pinecone using Retrieval-Augmented Generation to enhance content quality, and optimised the LLM.",
    ],
    results: [
      "Ensured the quality of 60K AI-generated courses.",
      "Cut course-creation time by 75%.",
    ],
    plates: [
      { device: "phone", caption: "Course intro screen — generated cover art and title" },
    ],
    meta: [
      { label: "Year", value: "2024" },
      { label: "Role", value: "Founding AI Engineer" },
      { label: "Stack", value: "Firebase · GCP · Pinecone · GPT-4" },
      { label: "Live", value: "learn.xyz ↗", link: true },
    ],
  },
  {
    slug: "meta",
    plate: "IV",
    year: "2022–23",
    medium: "data science · meta",
    title: "Data Science @ Meta",
    purpose:
      "The Metaverse needed clean data representations to build on. Numerous duplicate, fuzzy records existed across upstream systems.",
    work:
      "Built a deduplication data pipeline using the Levenshtein algorithm and subsampling for tractable scoring.",
    results: "Accelerated runtime by 20×. Mark Zuckerberg is happy. 😉",
    confidential: "Nothing to show — it's NDA.",
    meta: [
      { label: "Year", value: "2022" },
      { label: "Role", value: "Data Scientist" },
      { label: "Stack", value: "Python · Hive · Levenshtein" },
      { label: "Status", value: "Confidential" },
    ],
  },
];

export function getProject(slug: string): WorkProject | undefined {
  return WORK_PROJECTS.find((p) => p.slug === slug);
}
